[tool.poetry]
name = "voynich"
version = "0.1.0"
description = ""
authors = ["Sam Koepnick <git@koepnick.io>"]
readme = "README.md"
packages = [{include = "voynich"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
